const sampleProducts = [
  {
    brand: 'HyperX',
    category: 'RAM',
    description: 'This is 10 gb RAM memory ',
    discountedPrice: 40000,
    rating: 4.9,
    barcode: '13456',
    name: 'DDR4',
    url: 'www.google.com/apple',
    price: 200000,
    databaseUniqueId: '23',
  },
  {
    brand: 'Apple',
    category: 'Mobile',
    description: 'This is an Apple Mobile with 512 gb ram',
    discountedPrice: 123,
    rating: 4.3,
    barcode: '134556',
    name: 'Iphone 10',
    url: 'www.google.com/apple',
    price: 100000,
    databaseUniqueId: '1',
  },
  {
    brand: 'Apple',
    category: 'laptop',
    description: 'This is an Apple Laptop with 12p gb ram',
    discountedPrice: 40000,
    rating: 4.9,
    barcode: '13456',
    name: 'Macbook Pro',
    url: 'www.google.com/apple',
    price: 200000,
    databaseUniqueId: '3',
  },
  {
    brand: 'Levis',
    category: 'Pollo Shirt',
    description: 'Cotton Shirt',
    discountedPrice: 1000,
    rating: 5,
    barcode: '1345565',
    name: 'Oversized Pollo shirt',
    url: 'www.google.com/Levis',
    price: 1200,
    databaseUniqueId: '4',
  },
];

export default sampleProducts;
